services:
  web:
    build: .
    container_name: key_quest_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/key_quest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - PUBLIC_URL=/
      - DATABASE_URL=postgres://postgres:password@db:5432/key_quest_development
      - APP_VERSION=0.1.0
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
